-- PatientCare Oracle Database Script
-- This script creates the tables, sequences, and simple verification commands.
-- Run this file in SQL*Plus after connecting to your Oracle database.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE APPOINTMENT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PATIENT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE PATIENT_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE APPOINTMENT_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

CREATE TABLE PATIENT (
    PATIENT_ID VARCHAR2(20) PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    DOB DATE NOT NULL,
    AGE NUMBER,
    GENDER VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    ADDRESS VARCHAR2(250) NOT NULL,
    EMERGENCY_CONTACT_NAME VARCHAR2(100),
    EMERGENCY_CONTACT_PHONE VARCHAR2(20),
    BLOOD_GROUP VARCHAR2(10),
    ALLERGIES VARCHAR2(250),
    MEDICAL_CONDITIONS VARCHAR2(250),
    REASON_FOR_VISIT VARCHAR2(250) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID NUMBER PRIMARY KEY,
    PATIENT_ID VARCHAR2(20) NOT NULL,
    DEPARTMENT VARCHAR2(50) NOT NULL,
    DOCTOR VARCHAR2(100),
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_TIME VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_PATIENT_APPOINTMENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENT(PATIENT_ID)
        ON DELETE CASCADE
);

CREATE SEQUENCE PATIENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE APPOINTMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER PATIENT_BI
BEFORE INSERT ON PATIENT
FOR EACH ROW
BEGIN
    IF :NEW.PATIENT_ID IS NULL THEN
        :NEW.PATIENT_ID := 'P' || PATIENT_SEQ.NEXTVAL;
    END IF;
END;
/

-- Optional sample data for testing
-- INSERT INTO PATIENT (PATIENT_ID, FULL_NAME, DOB, AGE, GENDER, PHONE, EMAIL, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_PHONE, BLOOD_GROUP, ALLERGIES, MEDICAL_CONDITIONS, REASON_FOR_VISIT, CREATED_AT)
-- VALUES ('P1001', 'Sample Patient', TO_DATE('1995-05-10', 'YYYY-MM-DD'), 29, 'Male', '9876543210', 'sample@example.com', 'Sample Address', 'Emergency Person', '9999999999', 'O+', 'None', 'None', 'Fever and headache', SYSDATE);

-- Verification commands
SELECT TABLE_NAME FROM USER_TABLES;
DESC PATIENT;
DESC APPOINTMENT;

SELECT * FROM PATIENT;
SELECT * FROM APPOINTMENT;
