-- PatientCare Oracle Database Script
-- Creates the patient, appointment, and staff tables for the PatientCare project.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE APPOINTMENT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PATIENT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STAFF CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE PATIENT_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE APPOINTMENT_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE STAFF_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

CREATE TABLE PATIENT (
    PATIENT_ID VARCHAR2(20) PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    DOB DATE NOT NULL,
    AGE NUMBER,
    GENDER VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    ADDRESS VARCHAR2(250) NOT NULL,
    EMERGENCY_CONTACT_NAME VARCHAR2(100),
    EMERGENCY_CONTACT_PHONE VARCHAR2(20),
    BLOOD_GROUP VARCHAR2(10),
    ALLERGIES VARCHAR2(250),
    MEDICAL_CONDITIONS VARCHAR2(250),
    REASON_FOR_VISIT VARCHAR2(250) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID NUMBER PRIMARY KEY,
    PATIENT_ID VARCHAR2(20) NOT NULL,
    DEPARTMENT VARCHAR2(50) NOT NULL,
    DOCTOR VARCHAR2(100),
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_TIME VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'Scheduled',
    CONSTRAINT FK_PATIENT_APPOINTMENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENT(PATIENT_ID)
        ON DELETE CASCADE
);

CREATE TABLE STAFF (
    STAFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'Admin'
);

CREATE SEQUENCE PATIENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE APPOINTMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE STAFF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER PATIENT_BI
BEFORE INSERT ON PATIENT
FOR EACH ROW
BEGIN
    IF :NEW.PATIENT_ID IS NULL THEN
        :NEW.PATIENT_ID := 'P' || PATIENT_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER STAFF_BI
BEFORE INSERT ON STAFF
FOR EACH ROW
BEGIN
    IF :NEW.STAFF_ID IS NULL THEN
        :NEW.STAFF_ID := STAFF_SEQ.NEXTVAL;
    END IF;
END;
/

INSERT INTO STAFF (STAFF_ID, NAME, USERNAME, PASSWORD, ROLE)
VALUES (STAFF_SEQ.NEXTVAL, 'Admin User', 'admin', 'admin123', 'Admin');

COMMIT;

-- Optional sample patient records for testing
-- INSERT INTO PATIENT (PATIENT_ID, FULL_NAME, DOB, AGE, GENDER, PHONE, EMAIL, ADDRESS, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_PHONE, BLOOD_GROUP, ALLERGIES, MEDICAL_CONDITIONS, REASON_FOR_VISIT, CREATED_AT)
-- VALUES ('P1001', 'Sample Patient', TO_DATE('1995-05-10', 'YYYY-MM-DD'), 29, 'Male', '9876543210', 'sample@example.com', 'Sample Address', 'Emergency Person', '9999999999', 'O+', 'None', 'None', 'Fever and headache', SYSDATE);
-- INSERT INTO APPOINTMENT (APPOINTMENT_ID, PATIENT_ID, DEPARTMENT, DOCTOR, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS)
-- VALUES (APPOINTMENT_SEQ.NEXTVAL, 'P1001', 'General Medicine', 'Dr. Smith', SYSDATE, '10:30', 'Scheduled');

SELECT TABLE_NAME FROM USER_TABLES;
DESC PATIENT;
DESC APPOINTMENT;
DESC STAFF;

SELECT * FROM PATIENT;
SELECT * FROM APPOINTMENT;
SELECT * FROM STAFF;
